<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProdutoRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            ['nome' => 'required|max:100'],
            ['descricao' => 'required|max:255'],
            ['valor' => 'required|numeric'],
            ['tamanho' => 'required|min:100'],
            ['quantidade' => 'required|numeric']
        ];
    }

    public function messages()
    {
        return [
          'required' => 'O :attribute é obrigatorio'
        ];//parent::messages(); // TODO: Change the autogenerated stub
    }
}

/*
 *  $validator = Validator::make(
            ['nome' => Request::input('nome')],
            ['nome' => 'required|min:3']
        );

        if($validator->fails()){
            return redirect('/produto/novo');
        }
 * */